#!/bin/sh

### BEGIN INIT INFO
# Provides:          camerad
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Démon du système de surveillance 
### END INIT INFO


case "$1" in
  start)
    vlc=`ps aux | grep '/usr/bin/[v]lc'`
    raspivid=`ps aux | grep '[r]aspivid'`
    if [ -z "$vlc" ] && [ -z "$raspivid" ]
    then
    	echo "Démarrage de camerad"
    	/usr/bin/camera &
    else
        echo "camera est déjà lancé.";
    fi
    ;;

  stop)
    vlc=`ps aux | grep '/usr/bin/[v]lc'`
    raspivid=`ps aux | grep '[r]aspivid'`
    if [ -z "$vlc" ] && [ -z "$raspivid" ]
    then
	echo "camerad est déjà arrêté"
    else
      	echo "Arrêt de camerad"
    	killall camera vlc raspivid
    fi 
    ;;

  restart)
    stop;
    start;
    ;;

  status)
    vlc=`ps aux | grep '/usr/bin/[v]lc'`
    raspivid=`ps aux | grep '[r]aspivid'`
    camera=`ps aux | grep '/usr/bin/[c]amera'`
    if [ -z "$camera" ]
    then
         echo "camera est arrêté";
    else
         echo "camera est lancé";
    fi
    if  [ -z "$raspivid" ]
    then
        echo "raspivid est arrêté";
    else
        echo "raspivid est lancé";
    fi
    if [ -z "$vlc" ] 
    then 
         echo "vlc est arrêté";
    else
         echo "vlc est lancé";
    fi
    ;;

  *)
    echo "Usage: /etc/init.d/camerad {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0 
